version: '3'
services:
  bike-price-dashboard:
    image: bike-price-dashboard
    container_name: bike-price-dashboard
    build: .
    restart: always
    ports:
      - "8080:80"
#    expose:
#      - "8080"
