version: '3'
services:
  bike-price-dashboard:
    image: bike-price-dashboard
    container_name: bike-price-dashboard
    build: .
    restart: always
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
#  nginx:
#    image: nginx:alpine
#    restart: always
#    ports:
#      - "80:80"
#    depends_on:
#      - bike-price-dashboard